// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmmmessage.proto

#ifndef PROTOBUF_cmmmessage_2eproto__INCLUDED
#define PROTOBUF_cmmmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace isafetec {

// Internal implementation detail -- do not call these.
void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
void protobuf_AssignDesc_cmmmessage_2eproto();
void protobuf_ShutdownFile_cmmmessage_2eproto();

class BaseEquipInfo;
class BaseEquipInfoList;
class SimplePolicy;
class SimplePolicyList;
class TimeSpan;
class TimeSpanList;
class ClientSpan;
class ClientSpanList;
class SortType;
class SortTypeList;
class RelationShip;
class RelationShipList;

enum FILTER_TYPE {
  ONLINE_POLICY = 0,
  OUTLINE_POLICY = 1,
  COMMON_POLICY = 2
};
LIBPROTOBUF_EXPORT bool FILTER_TYPE_IsValid(int value);
const FILTER_TYPE FILTER_TYPE_MIN = ONLINE_POLICY;
const FILTER_TYPE FILTER_TYPE_MAX = COMMON_POLICY;
const int FILTER_TYPE_ARRAYSIZE = FILTER_TYPE_MAX + 1;

LIBPROTOBUF_EXPORT const ::google::protobuf::EnumDescriptor* FILTER_TYPE_descriptor();
inline const ::std::string& FILTER_TYPE_Name(FILTER_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    FILTER_TYPE_descriptor(), value);
}
inline bool FILTER_TYPE_Parse(
    const ::std::string& name, FILTER_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FILTER_TYPE>(
    FILTER_TYPE_descriptor(), name, value);
}
enum FILTERLIST_TYPE {
  BLACK_TYPE = 0,
  WHITE_TYPE = 1
};
LIBPROTOBUF_EXPORT bool FILTERLIST_TYPE_IsValid(int value);
const FILTERLIST_TYPE FILTERLIST_TYPE_MIN = BLACK_TYPE;
const FILTERLIST_TYPE FILTERLIST_TYPE_MAX = WHITE_TYPE;
const int FILTERLIST_TYPE_ARRAYSIZE = FILTERLIST_TYPE_MAX + 1;

LIBPROTOBUF_EXPORT const ::google::protobuf::EnumDescriptor* FILTERLIST_TYPE_descriptor();
inline const ::std::string& FILTERLIST_TYPE_Name(FILTERLIST_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    FILTERLIST_TYPE_descriptor(), value);
}
inline bool FILTERLIST_TYPE_Parse(
    const ::std::string& name, FILTERLIST_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FILTERLIST_TYPE>(
    FILTERLIST_TYPE_descriptor(), name, value);
}
enum FILTER_MODE {
  LEARNING_MODE = 0,
  WARING_MODE = 1,
  FORBIT_MODE = 2
};
LIBPROTOBUF_EXPORT bool FILTER_MODE_IsValid(int value);
const FILTER_MODE FILTER_MODE_MIN = LEARNING_MODE;
const FILTER_MODE FILTER_MODE_MAX = FORBIT_MODE;
const int FILTER_MODE_ARRAYSIZE = FILTER_MODE_MAX + 1;

LIBPROTOBUF_EXPORT const ::google::protobuf::EnumDescriptor* FILTER_MODE_descriptor();
inline const ::std::string& FILTER_MODE_Name(FILTER_MODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    FILTER_MODE_descriptor(), value);
}
inline bool FILTER_MODE_Parse(
    const ::std::string& name, FILTER_MODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FILTER_MODE>(
    FILTER_MODE_descriptor(), name, value);
}
// ===================================================================

class LIBPROTOBUF_EXPORT BaseEquipInfo : public ::google::protobuf::Message {
 public:
  BaseEquipInfo();
  virtual ~BaseEquipInfo();
  
  BaseEquipInfo(const BaseEquipInfo& from);
  
  inline BaseEquipInfo& operator=(const BaseEquipInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseEquipInfo& default_instance();
  
  void Swap(BaseEquipInfo* other);
  
  // implements Message ----------------------------------------------
  
  BaseEquipInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseEquipInfo& from);
  void MergeFrom(const BaseEquipInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string hddnum = 2;
  inline bool has_hddnum() const;
  inline void clear_hddnum();
  static const int kHddnumFieldNumber = 2;
  inline const ::std::string& hddnum() const;
  inline void set_hddnum(const ::std::string& value);
  inline void set_hddnum(const char* value);
  inline void set_hddnum(const char* value, size_t size);
  inline ::std::string* mutable_hddnum();
  inline ::std::string* release_hddnum();
  
  // optional string mac = 3;
  inline bool has_mac() const;
  inline void clear_mac();
  static const int kMacFieldNumber = 3;
  inline const ::std::string& mac() const;
  inline void set_mac(const ::std::string& value);
  inline void set_mac(const char* value);
  inline void set_mac(const char* value, size_t size);
  inline ::std::string* mutable_mac();
  inline ::std::string* release_mac();
  
  // optional string hostname = 4;
  inline bool has_hostname() const;
  inline void clear_hostname();
  static const int kHostnameFieldNumber = 4;
  inline const ::std::string& hostname() const;
  inline void set_hostname(const ::std::string& value);
  inline void set_hostname(const char* value);
  inline void set_hostname(const char* value, size_t size);
  inline ::std::string* mutable_hostname();
  inline ::std::string* release_hostname();
  
  // optional string ip = 5;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 5;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  
  // optional int32 equiptype = 6;
  inline bool has_equiptype() const;
  inline void clear_equiptype();
  static const int kEquiptypeFieldNumber = 6;
  inline ::google::protobuf::int32 equiptype() const;
  inline void set_equiptype(::google::protobuf::int32 value);
  
  // optional int32 state = 7;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 7;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);
  
  // optional double createon = 8;
  inline bool has_createon() const;
  inline void clear_createon();
  static const int kCreateonFieldNumber = 8;
  inline double createon() const;
  inline void set_createon(double value);
  
  // optional double lasthwscanon = 9;
  inline bool has_lasthwscanon() const;
  inline void clear_lasthwscanon();
  static const int kLasthwscanonFieldNumber = 9;
  inline double lasthwscanon() const;
  inline void set_lasthwscanon(double value);
  
  // optional double lastswscanon = 10;
  inline bool has_lastswscanon() const;
  inline void clear_lastswscanon();
  static const int kLastswscanonFieldNumber = 10;
  inline double lastswscanon() const;
  inline void set_lastswscanon(double value);
  
  // optional int32 createby = 11;
  inline bool has_createby() const;
  inline void clear_createby();
  static const int kCreatebyFieldNumber = 11;
  inline ::google::protobuf::int32 createby() const;
  inline void set_createby(::google::protobuf::int32 value);
  
  // optional int32 BindUserID = 12;
  inline bool has_binduserid() const;
  inline void clear_binduserid();
  static const int kBindUserIDFieldNumber = 12;
  inline ::google::protobuf::int32 binduserid() const;
  inline void set_binduserid(::google::protobuf::int32 value);
  
  // optional int32 IsOnline = 13;
  inline bool has_isonline() const;
  inline void clear_isonline();
  static const int kIsOnlineFieldNumber = 13;
  inline ::google::protobuf::int32 isonline() const;
  inline void set_isonline(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.BaseEquipInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_hddnum();
  inline void clear_has_hddnum();
  inline void set_has_mac();
  inline void clear_has_mac();
  inline void set_has_hostname();
  inline void clear_has_hostname();
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_equiptype();
  inline void clear_has_equiptype();
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_createon();
  inline void clear_has_createon();
  inline void set_has_lasthwscanon();
  inline void clear_has_lasthwscanon();
  inline void set_has_lastswscanon();
  inline void clear_has_lastswscanon();
  inline void set_has_createby();
  inline void clear_has_createby();
  inline void set_has_binduserid();
  inline void clear_has_binduserid();
  inline void set_has_isonline();
  inline void clear_has_isonline();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* hddnum_;
  ::std::string* mac_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 equiptype_;
  ::std::string* hostname_;
  ::std::string* ip_;
  double createon_;
  double lasthwscanon_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 createby_;
  double lastswscanon_;
  ::google::protobuf::int32 binduserid_;
  ::google::protobuf::int32 isonline_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(13 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static BaseEquipInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT BaseEquipInfoList : public ::google::protobuf::Message {
 public:
  BaseEquipInfoList();
  virtual ~BaseEquipInfoList();
  
  BaseEquipInfoList(const BaseEquipInfoList& from);
  
  inline BaseEquipInfoList& operator=(const BaseEquipInfoList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseEquipInfoList& default_instance();
  
  void Swap(BaseEquipInfoList* other);
  
  // implements Message ----------------------------------------------
  
  BaseEquipInfoList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseEquipInfoList& from);
  void MergeFrom(const BaseEquipInfoList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.BaseEquipInfo list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::BaseEquipInfo& list(int index) const;
  inline ::isafetec::BaseEquipInfo* mutable_list(int index);
  inline ::isafetec::BaseEquipInfo* BaseEquipInfoList::list_ReleaseAt(int index); 
  inline void BaseEquipInfoList::list_RemoveAt(int index); 
  inline ::isafetec::BaseEquipInfo* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::BaseEquipInfo >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::BaseEquipInfo >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.BaseEquipInfoList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::BaseEquipInfo > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static BaseEquipInfoList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT SimplePolicy : public ::google::protobuf::Message {
 public:
  SimplePolicy();
  virtual ~SimplePolicy();
  
  SimplePolicy(const SimplePolicy& from);
  
  inline SimplePolicy& operator=(const SimplePolicy& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimplePolicy& default_instance();
  
  void Swap(SimplePolicy* other);
  
  // implements Message ----------------------------------------------
  
  SimplePolicy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimplePolicy& from);
  void MergeFrom(const SimplePolicy& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional double last_time = 3;
  inline bool has_last_time() const;
  inline void clear_last_time();
  static const int kLastTimeFieldNumber = 3;
  inline double last_time() const;
  inline void set_last_time(double value);
  
  // optional int32 index = 4;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 4;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.SimplePolicy)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_last_time();
  inline void clear_has_last_time();
  inline void set_has_index();
  inline void clear_has_index();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 id_;
  double last_time_;
  ::google::protobuf::int32 index_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static SimplePolicy* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT SimplePolicyList : public ::google::protobuf::Message {
 public:
  SimplePolicyList();
  virtual ~SimplePolicyList();
  
  SimplePolicyList(const SimplePolicyList& from);
  
  inline SimplePolicyList& operator=(const SimplePolicyList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimplePolicyList& default_instance();
  
  void Swap(SimplePolicyList* other);
  
  // implements Message ----------------------------------------------
  
  SimplePolicyList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimplePolicyList& from);
  void MergeFrom(const SimplePolicyList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // repeated .isafetec.SimplePolicy list = 2;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 2;
  inline const ::isafetec::SimplePolicy& list(int index) const;
  inline ::isafetec::SimplePolicy* mutable_list(int index);
  inline ::isafetec::SimplePolicy* SimplePolicyList::list_ReleaseAt(int index); 
  inline void SimplePolicyList::list_RemoveAt(int index); 
  inline ::isafetec::SimplePolicy* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::SimplePolicy >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::SimplePolicy >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.SimplePolicyList)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::SimplePolicy > list_;
  ::google::protobuf::int32 type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static SimplePolicyList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT TimeSpan : public ::google::protobuf::Message {
 public:
  TimeSpan();
  virtual ~TimeSpan();
  
  TimeSpan(const TimeSpan& from);
  
  inline TimeSpan& operator=(const TimeSpan& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TimeSpan& default_instance();
  
  void Swap(TimeSpan* other);
  
  // implements Message ----------------------------------------------
  
  TimeSpan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TimeSpan& from);
  void MergeFrom(const TimeSpan& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string timeDesc = 2;
  inline bool has_timedesc() const;
  inline void clear_timedesc();
  static const int kTimeDescFieldNumber = 2;
  inline const ::std::string& timedesc() const;
  inline void set_timedesc(const ::std::string& value);
  inline void set_timedesc(const char* value);
  inline void set_timedesc(const char* value, size_t size);
  inline ::std::string* mutable_timedesc();
  inline ::std::string* release_timedesc();
  
  // optional double begin_time = 3;
  inline bool has_begin_time() const;
  inline void clear_begin_time();
  static const int kBeginTimeFieldNumber = 3;
  inline double begin_time() const;
  inline void set_begin_time(double value);
  
  // optional double end_time = 4;
  inline bool has_end_time() const;
  inline void clear_end_time();
  static const int kEndTimeFieldNumber = 4;
  inline double end_time() const;
  inline void set_end_time(double value);
  
  // @@protoc_insertion_point(class_scope:isafetec.TimeSpan)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_timedesc();
  inline void clear_has_timedesc();
  inline void set_has_begin_time();
  inline void clear_has_begin_time();
  inline void set_has_end_time();
  inline void clear_has_end_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* timedesc_;
  double begin_time_;
  double end_time_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static TimeSpan* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT TimeSpanList : public ::google::protobuf::Message {
 public:
  TimeSpanList();
  virtual ~TimeSpanList();
  
  TimeSpanList(const TimeSpanList& from);
  
  inline TimeSpanList& operator=(const TimeSpanList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TimeSpanList& default_instance();
  
  void Swap(TimeSpanList* other);
  
  // implements Message ----------------------------------------------
  
  TimeSpanList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TimeSpanList& from);
  void MergeFrom(const TimeSpanList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.TimeSpan list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::TimeSpan& list(int index) const;
  inline ::isafetec::TimeSpan* mutable_list(int index);
  inline ::isafetec::TimeSpan* TimeSpanList::list_ReleaseAt(int index); 
  inline void TimeSpanList::list_RemoveAt(int index); 
  inline ::isafetec::TimeSpan* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::TimeSpan >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::TimeSpan >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.TimeSpanList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::TimeSpan > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static TimeSpanList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ClientSpan : public ::google::protobuf::Message {
 public:
  ClientSpan();
  virtual ~ClientSpan();
  
  ClientSpan(const ClientSpan& from);
  
  inline ClientSpan& operator=(const ClientSpan& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientSpan& default_instance();
  
  void Swap(ClientSpan* other);
  
  // implements Message ----------------------------------------------
  
  ClientSpan* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientSpan& from);
  void MergeFrom(const ClientSpan& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // required uint32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);
  
  // optional int32 policyid = 3;
  inline bool has_policyid() const;
  inline void clear_policyid();
  static const int kPolicyidFieldNumber = 3;
  inline ::google::protobuf::int32 policyid() const;
  inline void set_policyid(::google::protobuf::int32 value);
  
  // optional int32 orderindex = 4;
  inline bool has_orderindex() const;
  inline void clear_orderindex();
  static const int kOrderindexFieldNumber = 4;
  inline ::google::protobuf::int32 orderindex() const;
  inline void set_orderindex(::google::protobuf::int32 value);
  
  // optional int32 isinherit = 5;
  inline bool has_isinherit() const;
  inline void clear_isinherit();
  static const int kIsinheritFieldNumber = 5;
  inline ::google::protobuf::int32 isinherit() const;
  inline void set_isinherit(::google::protobuf::int32 value);
  
  // optional int32 allowedinherit = 6;
  inline bool has_allowedinherit() const;
  inline void clear_allowedinherit();
  static const int kAllowedinheritFieldNumber = 6;
  inline ::google::protobuf::int32 allowedinherit() const;
  inline void set_allowedinherit(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.ClientSpan)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_policyid();
  inline void clear_has_policyid();
  inline void set_has_orderindex();
  inline void clear_has_orderindex();
  inline void set_has_isinherit();
  inline void clear_has_isinherit();
  inline void set_has_allowedinherit();
  inline void clear_has_allowedinherit();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 type_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::int32 policyid_;
  ::google::protobuf::int32 orderindex_;
  ::google::protobuf::int32 isinherit_;
  ::google::protobuf::int32 allowedinherit_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static ClientSpan* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ClientSpanList : public ::google::protobuf::Message {
 public:
  ClientSpanList();
  virtual ~ClientSpanList();
  
  ClientSpanList(const ClientSpanList& from);
  
  inline ClientSpanList& operator=(const ClientSpanList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientSpanList& default_instance();
  
  void Swap(ClientSpanList* other);
  
  // implements Message ----------------------------------------------
  
  ClientSpanList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientSpanList& from);
  void MergeFrom(const ClientSpanList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.ClientSpan list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::ClientSpan& list(int index) const;
  inline ::isafetec::ClientSpan* mutable_list(int index);
  inline ::isafetec::ClientSpan* ClientSpanList::list_ReleaseAt(int index); 
  inline void ClientSpanList::list_RemoveAt(int index); 
  inline ::isafetec::ClientSpan* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::ClientSpan >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::ClientSpan >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.ClientSpanList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::ClientSpan > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static ClientSpanList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT SortType : public ::google::protobuf::Message {
 public:
  SortType();
  virtual ~SortType();
  
  SortType(const SortType& from);
  
  inline SortType& operator=(const SortType& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SortType& default_instance();
  
  void Swap(SortType* other);
  
  // implements Message ----------------------------------------------
  
  SortType* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SortType& from);
  void MergeFrom(const SortType& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 plyType = 2;
  inline bool has_plytype() const;
  inline void clear_plytype();
  static const int kPlyTypeFieldNumber = 2;
  inline ::google::protobuf::int32 plytype() const;
  inline void set_plytype(::google::protobuf::int32 value);
  
  // optional string TypeDesc = 3;
  inline bool has_typedesc() const;
  inline void clear_typedesc();
  static const int kTypeDescFieldNumber = 3;
  inline const ::std::string& typedesc() const;
  inline void set_typedesc(const ::std::string& value);
  inline void set_typedesc(const char* value);
  inline void set_typedesc(const char* value, size_t size);
  inline ::std::string* mutable_typedesc();
  inline ::std::string* release_typedesc();
  
  // optional string ExeFileName = 4;
  inline bool has_exefilename() const;
  inline void clear_exefilename();
  static const int kExeFileNameFieldNumber = 4;
  inline const ::std::string& exefilename() const;
  inline void set_exefilename(const ::std::string& value);
  inline void set_exefilename(const char* value);
  inline void set_exefilename(const char* value, size_t size);
  inline ::std::string* mutable_exefilename();
  inline ::std::string* release_exefilename();
  
  // optional int32 FilterType = 5;
  inline bool has_filtertype() const;
  inline void clear_filtertype();
  static const int kFilterTypeFieldNumber = 5;
  inline ::google::protobuf::int32 filtertype() const;
  inline void set_filtertype(::google::protobuf::int32 value);
  
  // optional string FilterParam = 6;
  inline bool has_filterparam() const;
  inline void clear_filterparam();
  static const int kFilterParamFieldNumber = 6;
  inline const ::std::string& filterparam() const;
  inline void set_filterparam(const ::std::string& value);
  inline void set_filterparam(const char* value);
  inline void set_filterparam(const char* value, size_t size);
  inline ::std::string* mutable_filterparam();
  inline ::std::string* release_filterparam();
  
  // optional int32 modetype = 7;
  inline bool has_modetype() const;
  inline void clear_modetype();
  static const int kModetypeFieldNumber = 7;
  inline ::google::protobuf::int32 modetype() const;
  inline void set_modetype(::google::protobuf::int32 value);
  
  // optional int32 fileopType = 8;
  inline bool has_fileoptype() const;
  inline void clear_fileoptype();
  static const int kFileopTypeFieldNumber = 8;
  inline ::google::protobuf::int32 fileoptype() const;
  inline void set_fileoptype(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.SortType)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_plytype();
  inline void clear_has_plytype();
  inline void set_has_typedesc();
  inline void clear_has_typedesc();
  inline void set_has_exefilename();
  inline void clear_has_exefilename();
  inline void set_has_filtertype();
  inline void clear_has_filtertype();
  inline void set_has_filterparam();
  inline void clear_has_filterparam();
  inline void set_has_modetype();
  inline void clear_has_modetype();
  inline void set_has_fileoptype();
  inline void clear_has_fileoptype();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 plytype_;
  ::std::string* typedesc_;
  ::std::string* exefilename_;
  ::std::string* filterparam_;
  ::google::protobuf::int32 filtertype_;
  ::google::protobuf::int32 modetype_;
  ::google::protobuf::int32 fileoptype_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static SortType* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT SortTypeList : public ::google::protobuf::Message {
 public:
  SortTypeList();
  virtual ~SortTypeList();
  
  SortTypeList(const SortTypeList& from);
  
  inline SortTypeList& operator=(const SortTypeList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SortTypeList& default_instance();
  
  void Swap(SortTypeList* other);
  
  // implements Message ----------------------------------------------
  
  SortTypeList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SortTypeList& from);
  void MergeFrom(const SortTypeList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.SortType list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::SortType& list(int index) const;
  inline ::isafetec::SortType* mutable_list(int index);
  inline ::isafetec::SortType* SortTypeList::list_ReleaseAt(int index); 
  inline void SortTypeList::list_RemoveAt(int index); 
  inline ::isafetec::SortType* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::SortType >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::SortType >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.SortTypeList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::SortType > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static SortTypeList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT RelationShip : public ::google::protobuf::Message {
 public:
  RelationShip();
  virtual ~RelationShip();
  
  RelationShip(const RelationShip& from);
  
  inline RelationShip& operator=(const RelationShip& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RelationShip& default_instance();
  
  void Swap(RelationShip* other);
  
  // implements Message ----------------------------------------------
  
  RelationShip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RelationShip& from);
  void MergeFrom(const RelationShip& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 SortTypeID = 1;
  inline bool has_sorttypeid() const;
  inline void clear_sorttypeid();
  static const int kSortTypeIDFieldNumber = 1;
  inline ::google::protobuf::int32 sorttypeid() const;
  inline void set_sorttypeid(::google::protobuf::int32 value);
  
  // required int32 InofID = 2;
  inline bool has_inofid() const;
  inline void clear_inofid();
  static const int kInofIDFieldNumber = 2;
  inline ::google::protobuf::int32 inofid() const;
  inline void set_inofid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.RelationShip)
 private:
  inline void set_has_sorttypeid();
  inline void clear_has_sorttypeid();
  inline void set_has_inofid();
  inline void clear_has_inofid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 sorttypeid_;
  ::google::protobuf::int32 inofid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static RelationShip* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT RelationShipList : public ::google::protobuf::Message {
 public:
  RelationShipList();
  virtual ~RelationShipList();
  
  RelationShipList(const RelationShipList& from);
  
  inline RelationShipList& operator=(const RelationShipList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RelationShipList& default_instance();
  
  void Swap(RelationShipList* other);
  
  // implements Message ----------------------------------------------
  
  RelationShipList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RelationShipList& from);
  void MergeFrom(const RelationShipList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.RelationShip list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::RelationShip& list(int index) const;
  inline ::isafetec::RelationShip* mutable_list(int index);
  inline ::isafetec::RelationShip* RelationShipList::list_ReleaseAt(int index); 
  inline void RelationShipList::list_RemoveAt(int index); 
  inline ::isafetec::RelationShip* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::RelationShip >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::RelationShip >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.RelationShipList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::RelationShip > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_cmmmessage_2eproto();
  friend void protobuf_AssignDesc_cmmmessage_2eproto();
  friend void protobuf_ShutdownFile_cmmmessage_2eproto();
  
  void InitAsDefaultInstance();
  static RelationShipList* default_instance_;
};
// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace isafetec

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< isafetec::FILTER_TYPE>() {
  return isafetec::FILTER_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< isafetec::FILTERLIST_TYPE>() {
  return isafetec::FILTERLIST_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< isafetec::FILTER_MODE>() {
  return isafetec::FILTER_MODE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cmmmessage_2eproto__INCLUDED
