// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastream.proto

#ifndef PROTOBUF_datastream_2eproto__INCLUDED
#define PROTOBUF_datastream_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace isafetec {

// Internal implementation detail -- do not call these.
void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
void protobuf_AssignDesc_datastream_2eproto();
void protobuf_ShutdownFile_datastream_2eproto();

class datastream;
class MangerLogon;
class AdoConnect;
class MangerCheckUserResult;
class ReqLogFile;
class ReqLogFileList;
class PolicyChanged;
class OnlineCmd;
class OnlineCmdList;
class CltLogon;
class CltCheckUserResult;
class CltLocalCongfigInfo;
class ProductInfo;
class MgrSubscribeEvent;
class MgrSubscribeEventList;

enum ONLINE_CMD_TYPE {
  CMD_TIP = 0,
  CMD_EXEC = 1
};
LIBPROTOBUF_EXPORT bool ONLINE_CMD_TYPE_IsValid(int value);
const ONLINE_CMD_TYPE ONLINE_CMD_TYPE_MIN = CMD_TIP;
const ONLINE_CMD_TYPE ONLINE_CMD_TYPE_MAX = CMD_EXEC;
const int ONLINE_CMD_TYPE_ARRAYSIZE = ONLINE_CMD_TYPE_MAX + 1;

LIBPROTOBUF_EXPORT const ::google::protobuf::EnumDescriptor* ONLINE_CMD_TYPE_descriptor();
inline const ::std::string& ONLINE_CMD_TYPE_Name(ONLINE_CMD_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    ONLINE_CMD_TYPE_descriptor(), value);
}
inline bool ONLINE_CMD_TYPE_Parse(
    const ::std::string& name, ONLINE_CMD_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ONLINE_CMD_TYPE>(
    ONLINE_CMD_TYPE_descriptor(), name, value);
}
enum UserLogonType {
  NO_CHECK = 0,
  CHECK_BY_IST = 1,
  CHECK_BY_AD = 2,
  CHECK_BY_OTHER = 3
};
LIBPROTOBUF_EXPORT bool UserLogonType_IsValid(int value);
const UserLogonType UserLogonType_MIN = NO_CHECK;
const UserLogonType UserLogonType_MAX = CHECK_BY_OTHER;
const int UserLogonType_ARRAYSIZE = UserLogonType_MAX + 1;

LIBPROTOBUF_EXPORT const ::google::protobuf::EnumDescriptor* UserLogonType_descriptor();
inline const ::std::string& UserLogonType_Name(UserLogonType value) {
  return ::google::protobuf::internal::NameOfEnum(
    UserLogonType_descriptor(), value);
}
inline bool UserLogonType_Parse(
    const ::std::string& name, UserLogonType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UserLogonType>(
    UserLogonType_descriptor(), name, value);
}
// ===================================================================

class LIBPROTOBUF_EXPORT datastream : public ::google::protobuf::Message {
 public:
  datastream();
  virtual ~datastream();
  
  datastream(const datastream& from);
  
  inline datastream& operator=(const datastream& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const datastream& default_instance();
  
  void Swap(datastream* other);
  
  // implements Message ----------------------------------------------
  
  datastream* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const datastream& from);
  void MergeFrom(const datastream& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 col = 1;
  inline bool has_col() const;
  inline void clear_col();
  static const int kColFieldNumber = 1;
  inline ::google::protobuf::int32 col() const;
  inline void set_col(::google::protobuf::int32 value);
  
  // required int32 row = 2;
  inline bool has_row() const;
  inline void clear_row();
  static const int kRowFieldNumber = 2;
  inline ::google::protobuf::int32 row() const;
  inline void set_row(::google::protobuf::int32 value);
  
  // repeated string val = 3;
  inline int val_size() const;
  inline void clear_val();
  static const int kValFieldNumber = 3;
  inline const ::std::string& val(int index) const;
  inline ::std::string* mutable_val(int index);
  inline void set_val(int index, const ::std::string& value);
  inline void set_val(int index, const char* value);
  inline void set_val(int index, const char* value, size_t size);
  inline ::std::string* add_val();
  inline void add_val(const ::std::string& value);
  inline void add_val(const char* value);
  inline void add_val(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& val() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_val();
  
  // @@protoc_insertion_point(class_scope:isafetec.datastream)
 private:
  inline void set_has_col();
  inline void clear_has_col();
  inline void set_has_row();
  inline void clear_has_row();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 col_;
  ::google::protobuf::int32 row_;
  ::google::protobuf::RepeatedPtrField< ::std::string> val_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static datastream* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT MangerLogon : public ::google::protobuf::Message {
 public:
  MangerLogon();
  virtual ~MangerLogon();
  
  MangerLogon(const MangerLogon& from);
  
  inline MangerLogon& operator=(const MangerLogon& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MangerLogon& default_instance();
  
  void Swap(MangerLogon* other);
  
  // implements Message ----------------------------------------------
  
  MangerLogon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MangerLogon& from);
  void MergeFrom(const MangerLogon& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional string pwd = 3;
  inline bool has_pwd() const;
  inline void clear_pwd();
  static const int kPwdFieldNumber = 3;
  inline const ::std::string& pwd() const;
  inline void set_pwd(const ::std::string& value);
  inline void set_pwd(const char* value);
  inline void set_pwd(const char* value, size_t size);
  inline ::std::string* mutable_pwd();
  inline ::std::string* release_pwd();
  
  // @@protoc_insertion_point(class_scope:isafetec.MangerLogon)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_pwd();
  inline void clear_has_pwd();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::std::string* pwd_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static MangerLogon* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT AdoConnect : public ::google::protobuf::Message {
 public:
  AdoConnect();
  virtual ~AdoConnect();
  
  AdoConnect(const AdoConnect& from);
  
  inline AdoConnect& operator=(const AdoConnect& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const AdoConnect& default_instance();
  
  void Swap(AdoConnect* other);
  
  // implements Message ----------------------------------------------
  
  AdoConnect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdoConnect& from);
  void MergeFrom(const AdoConnect& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string ip = 1;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 1;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  
  // optional string port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline const ::std::string& port() const;
  inline void set_port(const ::std::string& value);
  inline void set_port(const char* value);
  inline void set_port(const char* value, size_t size);
  inline ::std::string* mutable_port();
  inline ::std::string* release_port();
  
  // optional string user = 3;
  inline bool has_user() const;
  inline void clear_user();
  static const int kUserFieldNumber = 3;
  inline const ::std::string& user() const;
  inline void set_user(const ::std::string& value);
  inline void set_user(const char* value);
  inline void set_user(const char* value, size_t size);
  inline ::std::string* mutable_user();
  inline ::std::string* release_user();
  
  // optional string pwd = 4;
  inline bool has_pwd() const;
  inline void clear_pwd();
  static const int kPwdFieldNumber = 4;
  inline const ::std::string& pwd() const;
  inline void set_pwd(const ::std::string& value);
  inline void set_pwd(const char* value);
  inline void set_pwd(const char* value, size_t size);
  inline ::std::string* mutable_pwd();
  inline ::std::string* release_pwd();
  
  // optional string db = 5;
  inline bool has_db() const;
  inline void clear_db();
  static const int kDbFieldNumber = 5;
  inline const ::std::string& db() const;
  inline void set_db(const ::std::string& value);
  inline void set_db(const char* value);
  inline void set_db(const char* value, size_t size);
  inline ::std::string* mutable_db();
  inline ::std::string* release_db();
  
  // @@protoc_insertion_point(class_scope:isafetec.AdoConnect)
 private:
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_user();
  inline void clear_has_user();
  inline void set_has_pwd();
  inline void clear_has_pwd();
  inline void set_has_db();
  inline void clear_has_db();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ip_;
  ::std::string* port_;
  ::std::string* user_;
  ::std::string* pwd_;
  ::std::string* db_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static AdoConnect* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT MangerCheckUserResult : public ::google::protobuf::Message {
 public:
  MangerCheckUserResult();
  virtual ~MangerCheckUserResult();
  
  MangerCheckUserResult(const MangerCheckUserResult& from);
  
  inline MangerCheckUserResult& operator=(const MangerCheckUserResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MangerCheckUserResult& default_instance();
  
  void Swap(MangerCheckUserResult* other);
  
  // implements Message ----------------------------------------------
  
  MangerCheckUserResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MangerCheckUserResult& from);
  void MergeFrom(const MangerCheckUserResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional .isafetec.AdoConnect ado = 2;
  inline bool has_ado() const;
  inline void clear_ado();
  static const int kAdoFieldNumber = 2;
  inline const ::isafetec::AdoConnect& ado() const;
  inline ::isafetec::AdoConnect* mutable_ado();
  inline ::isafetec::AdoConnect* release_ado();
  
  // @@protoc_insertion_point(class_scope:isafetec.MangerCheckUserResult)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_ado();
  inline void clear_has_ado();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::isafetec::AdoConnect* ado_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static MangerCheckUserResult* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ReqLogFile : public ::google::protobuf::Message {
 public:
  ReqLogFile();
  virtual ~ReqLogFile();
  
  ReqLogFile(const ReqLogFile& from);
  
  inline ReqLogFile& operator=(const ReqLogFile& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqLogFile& default_instance();
  
  void Swap(ReqLogFile* other);
  
  // implements Message ----------------------------------------------
  
  ReqLogFile* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReqLogFile& from);
  void MergeFrom(const ReqLogFile& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  
  // @@protoc_insertion_point(class_scope:isafetec.ReqLogFile)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_path();
  inline void clear_has_path();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* path_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static ReqLogFile* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ReqLogFileList : public ::google::protobuf::Message {
 public:
  ReqLogFileList();
  virtual ~ReqLogFileList();
  
  ReqLogFileList(const ReqLogFileList& from);
  
  inline ReqLogFileList& operator=(const ReqLogFileList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqLogFileList& default_instance();
  
  void Swap(ReqLogFileList* other);
  
  // implements Message ----------------------------------------------
  
  ReqLogFileList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReqLogFileList& from);
  void MergeFrom(const ReqLogFileList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.ReqLogFile list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::ReqLogFile& list(int index) const;
  inline ::isafetec::ReqLogFile* mutable_list(int index);
  inline ::isafetec::ReqLogFile* ReqLogFileList::list_ReleaseAt(int index); 
  inline void ReqLogFileList::list_RemoveAt(int index); 
  inline ::isafetec::ReqLogFile* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::ReqLogFile >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::ReqLogFile >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.ReqLogFileList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::ReqLogFile > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static ReqLogFileList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PolicyChanged : public ::google::protobuf::Message {
 public:
  PolicyChanged();
  virtual ~PolicyChanged();
  
  PolicyChanged(const PolicyChanged& from);
  
  inline PolicyChanged& operator=(const PolicyChanged& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PolicyChanged& default_instance();
  
  void Swap(PolicyChanged* other);
  
  // implements Message ----------------------------------------------
  
  PolicyChanged* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PolicyChanged& from);
  void MergeFrom(const PolicyChanged& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated int32 id = 1;
  inline int id_size() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id(int index) const;
  inline void set_id(int index, ::google::protobuf::int32 value);
  inline void add_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_id();
  
  // optional int32 type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // optional int32 policyid = 3;
  inline bool has_policyid() const;
  inline void clear_policyid();
  static const int kPolicyidFieldNumber = 3;
  inline ::google::protobuf::int32 policyid() const;
  inline void set_policyid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.PolicyChanged)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_policyid();
  inline void clear_has_policyid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > id_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 policyid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static PolicyChanged* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT OnlineCmd : public ::google::protobuf::Message {
 public:
  OnlineCmd();
  virtual ~OnlineCmd();
  
  OnlineCmd(const OnlineCmd& from);
  
  inline OnlineCmd& operator=(const OnlineCmd& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const OnlineCmd& default_instance();
  
  void Swap(OnlineCmd* other);
  
  // implements Message ----------------------------------------------
  
  OnlineCmd* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnlineCmd& from);
  void MergeFrom(const OnlineCmd& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional .isafetec.ONLINE_CMD_TYPE type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline isafetec::ONLINE_CMD_TYPE type() const;
  inline void set_type(isafetec::ONLINE_CMD_TYPE value);
  
  // optional string msg = 3;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 3;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  
  // @@protoc_insertion_point(class_scope:isafetec.OnlineCmd)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_msg();
  inline void clear_has_msg();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  int type_;
  ::std::string* msg_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static OnlineCmd* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT OnlineCmdList : public ::google::protobuf::Message {
 public:
  OnlineCmdList();
  virtual ~OnlineCmdList();
  
  OnlineCmdList(const OnlineCmdList& from);
  
  inline OnlineCmdList& operator=(const OnlineCmdList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const OnlineCmdList& default_instance();
  
  void Swap(OnlineCmdList* other);
  
  // implements Message ----------------------------------------------
  
  OnlineCmdList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OnlineCmdList& from);
  void MergeFrom(const OnlineCmdList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.OnlineCmd list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::OnlineCmd& list(int index) const;
  inline ::isafetec::OnlineCmd* mutable_list(int index);
  inline ::isafetec::OnlineCmd* OnlineCmdList::list_ReleaseAt(int index); 
  inline void OnlineCmdList::list_RemoveAt(int index); 
  inline ::isafetec::OnlineCmd* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::OnlineCmd >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::OnlineCmd >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.OnlineCmdList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::OnlineCmd > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static OnlineCmdList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT CltLogon : public ::google::protobuf::Message {
 public:
  CltLogon();
  virtual ~CltLogon();
  
  CltLogon(const CltLogon& from);
  
  inline CltLogon& operator=(const CltLogon& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CltLogon& default_instance();
  
  void Swap(CltLogon* other);
  
  // implements Message ----------------------------------------------
  
  CltLogon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CltLogon& from);
  void MergeFrom(const CltLogon& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // optional string pwd = 3;
  inline bool has_pwd() const;
  inline void clear_pwd();
  static const int kPwdFieldNumber = 3;
  inline const ::std::string& pwd() const;
  inline void set_pwd(const ::std::string& value);
  inline void set_pwd(const char* value);
  inline void set_pwd(const char* value, size_t size);
  inline ::std::string* mutable_pwd();
  inline ::std::string* release_pwd();
  
  // @@protoc_insertion_point(class_scope:isafetec.CltLogon)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_pwd();
  inline void clear_has_pwd();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::std::string* pwd_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static CltLogon* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT CltCheckUserResult : public ::google::protobuf::Message {
 public:
  CltCheckUserResult();
  virtual ~CltCheckUserResult();
  
  CltCheckUserResult(const CltCheckUserResult& from);
  
  inline CltCheckUserResult& operator=(const CltCheckUserResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CltCheckUserResult& default_instance();
  
  void Swap(CltCheckUserResult* other);
  
  // implements Message ----------------------------------------------
  
  CltCheckUserResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CltCheckUserResult& from);
  void MergeFrom(const CltCheckUserResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional int32 role_type = 2;
  inline bool has_role_type() const;
  inline void clear_role_type();
  static const int kRoleTypeFieldNumber = 2;
  inline ::google::protobuf::int32 role_type() const;
  inline void set_role_type(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.CltCheckUserResult)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_role_type();
  inline void clear_has_role_type();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 role_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static CltCheckUserResult* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT CltLocalCongfigInfo : public ::google::protobuf::Message {
 public:
  CltLocalCongfigInfo();
  virtual ~CltLocalCongfigInfo();
  
  CltLocalCongfigInfo(const CltLocalCongfigInfo& from);
  
  inline CltLocalCongfigInfo& operator=(const CltLocalCongfigInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CltLocalCongfigInfo& default_instance();
  
  void Swap(CltLocalCongfigInfo* other);
  
  // implements Message ----------------------------------------------
  
  CltLocalCongfigInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CltLocalCongfigInfo& from);
  void MergeFrom(const CltLocalCongfigInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 product_code = 1;
  inline bool has_product_code() const;
  inline void clear_product_code();
  static const int kProductCodeFieldNumber = 1;
  inline ::google::protobuf::int32 product_code() const;
  inline void set_product_code(::google::protobuf::int32 value);
  
  // optional int32 debug_log = 2;
  inline bool has_debug_log() const;
  inline void clear_debug_log();
  static const int kDebugLogFieldNumber = 2;
  inline ::google::protobuf::int32 debug_log() const;
  inline void set_debug_log(::google::protobuf::int32 value);
  
  // optional int32 net_state = 3;
  inline bool has_net_state() const;
  inline void clear_net_state();
  static const int kNetStateFieldNumber = 3;
  inline ::google::protobuf::int32 net_state() const;
  inline void set_net_state(::google::protobuf::int32 value);
  
  // optional int32 user_id = 4;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 4;
  inline ::google::protobuf::int32 user_id() const;
  inline void set_user_id(::google::protobuf::int32 value);
  
  // optional string user_name = 5;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 5;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  
  // @@protoc_insertion_point(class_scope:isafetec.CltLocalCongfigInfo)
 private:
  inline void set_has_product_code();
  inline void clear_has_product_code();
  inline void set_has_debug_log();
  inline void clear_has_debug_log();
  inline void set_has_net_state();
  inline void clear_has_net_state();
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_user_name();
  inline void clear_has_user_name();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 product_code_;
  ::google::protobuf::int32 debug_log_;
  ::google::protobuf::int32 net_state_;
  ::google::protobuf::int32 user_id_;
  ::std::string* user_name_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static CltLocalCongfigInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ProductInfo : public ::google::protobuf::Message {
 public:
  ProductInfo();
  virtual ~ProductInfo();
  
  ProductInfo(const ProductInfo& from);
  
  inline ProductInfo& operator=(const ProductInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProductInfo& default_instance();
  
  void Swap(ProductInfo* other);
  
  // implements Message ----------------------------------------------
  
  ProductInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProductInfo& from);
  void MergeFrom(const ProductInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 product_code = 1;
  inline bool has_product_code() const;
  inline void clear_product_code();
  static const int kProductCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 product_code() const;
  inline void set_product_code(::google::protobuf::uint32 value);
  
  // optional uint32 sub_code = 2;
  inline bool has_sub_code() const;
  inline void clear_sub_code();
  static const int kSubCodeFieldNumber = 2;
  inline ::google::protobuf::uint32 sub_code() const;
  inline void set_sub_code(::google::protobuf::uint32 value);
  
  // optional bool demo_version = 3;
  inline bool has_demo_version() const;
  inline void clear_demo_version();
  static const int kDemoVersionFieldNumber = 3;
  inline bool demo_version() const;
  inline void set_demo_version(bool value);
  
  // optional int32 user_count = 4;
  inline bool has_user_count() const;
  inline void clear_user_count();
  static const int kUserCountFieldNumber = 4;
  inline ::google::protobuf::int32 user_count() const;
  inline void set_user_count(::google::protobuf::int32 value);
  
  // optional .isafetec.UserLogonType user_check_type = 5;
  inline bool has_user_check_type() const;
  inline void clear_user_check_type();
  static const int kUserCheckTypeFieldNumber = 5;
  inline isafetec::UserLogonType user_check_type() const;
  inline void set_user_check_type(isafetec::UserLogonType value);
  
  // optional bool need_ui_process = 6;
  inline bool has_need_ui_process() const;
  inline void clear_need_ui_process();
  static const int kNeedUiProcessFieldNumber = 6;
  inline bool need_ui_process() const;
  inline void set_need_ui_process(bool value);
  
  // optional bool logon_atonce = 7;
  inline bool has_logon_atonce() const;
  inline void clear_logon_atonce();
  static const int kLogonAtonceFieldNumber = 7;
  inline bool logon_atonce() const;
  inline void set_logon_atonce(bool value);
  
  // optional string version_info = 8;
  inline bool has_version_info() const;
  inline void clear_version_info();
  static const int kVersionInfoFieldNumber = 8;
  inline const ::std::string& version_info() const;
  inline void set_version_info(const ::std::string& value);
  inline void set_version_info(const char* value);
  inline void set_version_info(const char* value, size_t size);
  inline ::std::string* mutable_version_info();
  inline ::std::string* release_version_info();
  
  // optional string ad_server = 9;
  inline bool has_ad_server() const;
  inline void clear_ad_server();
  static const int kAdServerFieldNumber = 9;
  inline const ::std::string& ad_server() const;
  inline void set_ad_server(const ::std::string& value);
  inline void set_ad_server(const char* value);
  inline void set_ad_server(const char* value, size_t size);
  inline ::std::string* mutable_ad_server();
  inline ::std::string* release_ad_server();
  
  // optional string other_server = 10;
  inline bool has_other_server() const;
  inline void clear_other_server();
  static const int kOtherServerFieldNumber = 10;
  inline const ::std::string& other_server() const;
  inline void set_other_server(const ::std::string& value);
  inline void set_other_server(const char* value);
  inline void set_other_server(const char* value, size_t size);
  inline ::std::string* mutable_other_server();
  inline ::std::string* release_other_server();
  
  // @@protoc_insertion_point(class_scope:isafetec.ProductInfo)
 private:
  inline void set_has_product_code();
  inline void clear_has_product_code();
  inline void set_has_sub_code();
  inline void clear_has_sub_code();
  inline void set_has_demo_version();
  inline void clear_has_demo_version();
  inline void set_has_user_count();
  inline void clear_has_user_count();
  inline void set_has_user_check_type();
  inline void clear_has_user_check_type();
  inline void set_has_need_ui_process();
  inline void clear_has_need_ui_process();
  inline void set_has_logon_atonce();
  inline void clear_has_logon_atonce();
  inline void set_has_version_info();
  inline void clear_has_version_info();
  inline void set_has_ad_server();
  inline void clear_has_ad_server();
  inline void set_has_other_server();
  inline void clear_has_other_server();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 product_code_;
  ::google::protobuf::uint32 sub_code_;
  ::google::protobuf::int32 user_count_;
  int user_check_type_;
  ::std::string* version_info_;
  ::std::string* ad_server_;
  ::std::string* other_server_;
  bool demo_version_;
  bool need_ui_process_;
  bool logon_atonce_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static ProductInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT MgrSubscribeEvent : public ::google::protobuf::Message {
 public:
  MgrSubscribeEvent();
  virtual ~MgrSubscribeEvent();
  
  MgrSubscribeEvent(const MgrSubscribeEvent& from);
  
  inline MgrSubscribeEvent& operator=(const MgrSubscribeEvent& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MgrSubscribeEvent& default_instance();
  
  void Swap(MgrSubscribeEvent* other);
  
  // implements Message ----------------------------------------------
  
  MgrSubscribeEvent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MgrSubscribeEvent& from);
  void MergeFrom(const MgrSubscribeEvent& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 equip_id = 1;
  inline bool has_equip_id() const;
  inline void clear_equip_id();
  static const int kEquipIdFieldNumber = 1;
  inline ::google::protobuf::int32 equip_id() const;
  inline void set_equip_id(::google::protobuf::int32 value);
  
  // optional int32 user_id = 2;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  inline ::google::protobuf::int32 user_id() const;
  inline void set_user_id(::google::protobuf::int32 value);
  
  // optional uint32 event_mask = 3;
  inline bool has_event_mask() const;
  inline void clear_event_mask();
  static const int kEventMaskFieldNumber = 3;
  inline ::google::protobuf::uint32 event_mask() const;
  inline void set_event_mask(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.MgrSubscribeEvent)
 private:
  inline void set_has_equip_id();
  inline void clear_has_equip_id();
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_event_mask();
  inline void clear_has_event_mask();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 equip_id_;
  ::google::protobuf::int32 user_id_;
  ::google::protobuf::uint32 event_mask_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static MgrSubscribeEvent* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT MgrSubscribeEventList : public ::google::protobuf::Message {
 public:
  MgrSubscribeEventList();
  virtual ~MgrSubscribeEventList();
  
  MgrSubscribeEventList(const MgrSubscribeEventList& from);
  
  inline MgrSubscribeEventList& operator=(const MgrSubscribeEventList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MgrSubscribeEventList& default_instance();
  
  void Swap(MgrSubscribeEventList* other);
  
  // implements Message ----------------------------------------------
  
  MgrSubscribeEventList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MgrSubscribeEventList& from);
  void MergeFrom(const MgrSubscribeEventList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.MgrSubscribeEvent list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::MgrSubscribeEvent& list(int index) const;
  inline ::isafetec::MgrSubscribeEvent* mutable_list(int index);
  inline ::isafetec::MgrSubscribeEvent* MgrSubscribeEventList::list_ReleaseAt(int index); 
  inline void MgrSubscribeEventList::list_RemoveAt(int index); 
  inline ::isafetec::MgrSubscribeEvent* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::MgrSubscribeEvent >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::MgrSubscribeEvent >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.MgrSubscribeEventList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::MgrSubscribeEvent > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_datastream_2eproto();
  friend void protobuf_AssignDesc_datastream_2eproto();
  friend void protobuf_ShutdownFile_datastream_2eproto();
  
  void InitAsDefaultInstance();
  static MgrSubscribeEventList* default_instance_;
};
// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace isafetec

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< isafetec::ONLINE_CMD_TYPE>() {
  return isafetec::ONLINE_CMD_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< isafetec::UserLogonType>() {
  return isafetec::UserLogonType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_datastream_2eproto__INCLUDED
