// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: popedom.proto

#ifndef PROTOBUF_popedom_2eproto__INCLUDED
#define PROTOBUF_popedom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace isafetec {

// Internal implementation detail -- do not call these.
void LIBPROTOBUF_EXPORT protobuf_AddDesc_popedom_2eproto();
void protobuf_AssignDesc_popedom_2eproto();
void protobuf_ShutdownFile_popedom_2eproto();

class PopedomInfo;
class PopedomInfoList;
class PopedomInfoNode;
class PopedomNodeList;

// ===================================================================

class LIBPROTOBUF_EXPORT PopedomInfo : public ::google::protobuf::Message {
 public:
  PopedomInfo();
  virtual ~PopedomInfo();
  
  PopedomInfo(const PopedomInfo& from);
  
  inline PopedomInfo& operator=(const PopedomInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PopedomInfo& default_instance();
  
  void Swap(PopedomInfo* other);
  
  // implements Message ----------------------------------------------
  
  PopedomInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PopedomInfo& from);
  void MergeFrom(const PopedomInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional int32 maintype = 2;
  inline bool has_maintype() const;
  inline void clear_maintype();
  static const int kMaintypeFieldNumber = 2;
  inline ::google::protobuf::int32 maintype() const;
  inline void set_maintype(::google::protobuf::int32 value);
  
  // optional int32 type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);
  
  // optional string typename = 4;
  inline bool has_typename_() const;
  inline void clear_typename_();
  static const int kTypenameFieldNumber = 4;
  inline const ::std::string& typename_() const;
  inline void set_typename_(const ::std::string& value);
  inline void set_typename_(const char* value);
  inline void set_typename_(const char* value, size_t size);
  inline ::std::string* mutable_typename_();
  inline ::std::string* release_typename_();
  
  // optional string iconpath = 5;
  inline bool has_iconpath() const;
  inline void clear_iconpath();
  static const int kIconpathFieldNumber = 5;
  inline const ::std::string& iconpath() const;
  inline void set_iconpath(const ::std::string& value);
  inline void set_iconpath(const char* value);
  inline void set_iconpath(const char* value, size_t size);
  inline ::std::string* mutable_iconpath();
  inline ::std::string* release_iconpath();
  
  // optional int32 attributetype = 6;
  inline bool has_attributetype() const;
  inline void clear_attributetype();
  static const int kAttributetypeFieldNumber = 6;
  inline ::google::protobuf::int32 attributetype() const;
  inline void set_attributetype(::google::protobuf::int32 value);
  
  // optional int32 menushow = 7;
  inline bool has_menushow() const;
  inline void clear_menushow();
  static const int kMenushowFieldNumber = 7;
  inline ::google::protobuf::int32 menushow() const;
  inline void set_menushow(::google::protobuf::int32 value);
  
  // optional int32 menuindex = 8;
  inline bool has_menuindex() const;
  inline void clear_menuindex();
  static const int kMenuindexFieldNumber = 8;
  inline ::google::protobuf::int32 menuindex() const;
  inline void set_menuindex(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.PopedomInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_maintype();
  inline void clear_has_maintype();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_typename_();
  inline void clear_has_typename_();
  inline void set_has_iconpath();
  inline void clear_has_iconpath();
  inline void set_has_attributetype();
  inline void clear_has_attributetype();
  inline void set_has_menushow();
  inline void clear_has_menushow();
  inline void set_has_menuindex();
  inline void clear_has_menuindex();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 maintype_;
  ::std::string* typename__;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 attributetype_;
  ::std::string* iconpath_;
  ::google::protobuf::int32 menushow_;
  ::google::protobuf::int32 menuindex_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(8 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_popedom_2eproto();
  friend void protobuf_AssignDesc_popedom_2eproto();
  friend void protobuf_ShutdownFile_popedom_2eproto();
  
  void InitAsDefaultInstance();
  static PopedomInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PopedomInfoList : public ::google::protobuf::Message {
 public:
  PopedomInfoList();
  virtual ~PopedomInfoList();
  
  PopedomInfoList(const PopedomInfoList& from);
  
  inline PopedomInfoList& operator=(const PopedomInfoList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PopedomInfoList& default_instance();
  
  void Swap(PopedomInfoList* other);
  
  // implements Message ----------------------------------------------
  
  PopedomInfoList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PopedomInfoList& from);
  void MergeFrom(const PopedomInfoList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.PopedomInfo list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::PopedomInfo& list(int index) const;
  inline ::isafetec::PopedomInfo* mutable_list(int index);
  inline ::isafetec::PopedomInfo* PopedomInfoList::list_ReleaseAt(int index); 
  inline void PopedomInfoList::list_RemoveAt(int index); 
  inline ::isafetec::PopedomInfo* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfo >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfo >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.PopedomInfoList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfo > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_popedom_2eproto();
  friend void protobuf_AssignDesc_popedom_2eproto();
  friend void protobuf_ShutdownFile_popedom_2eproto();
  
  void InitAsDefaultInstance();
  static PopedomInfoList* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PopedomInfoNode : public ::google::protobuf::Message {
 public:
  PopedomInfoNode();
  virtual ~PopedomInfoNode();
  
  PopedomInfoNode(const PopedomInfoNode& from);
  
  inline PopedomInfoNode& operator=(const PopedomInfoNode& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PopedomInfoNode& default_instance();
  
  void Swap(PopedomInfoNode* other);
  
  // implements Message ----------------------------------------------
  
  PopedomInfoNode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PopedomInfoNode& from);
  void MergeFrom(const PopedomInfoNode& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional int32 maintype = 2;
  inline bool has_maintype() const;
  inline void clear_maintype();
  static const int kMaintypeFieldNumber = 2;
  inline ::google::protobuf::int32 maintype() const;
  inline void set_maintype(::google::protobuf::int32 value);
  
  // optional string mainname = 3;
  inline bool has_mainname() const;
  inline void clear_mainname();
  static const int kMainnameFieldNumber = 3;
  inline const ::std::string& mainname() const;
  inline void set_mainname(const ::std::string& value);
  inline void set_mainname(const char* value);
  inline void set_mainname(const char* value, size_t size);
  inline ::std::string* mutable_mainname();
  inline ::std::string* release_mainname();
  
  // optional string mainiconpath = 4;
  inline bool has_mainiconpath() const;
  inline void clear_mainiconpath();
  static const int kMainiconpathFieldNumber = 4;
  inline const ::std::string& mainiconpath() const;
  inline void set_mainiconpath(const ::std::string& value);
  inline void set_mainiconpath(const char* value);
  inline void set_mainiconpath(const char* value, size_t size);
  inline ::std::string* mutable_mainiconpath();
  inline ::std::string* release_mainiconpath();
  
  // optional .isafetec.PopedomInfoList list = 5;
  inline bool has_list() const;
  inline void clear_list();
  static const int kListFieldNumber = 5;
  inline const ::isafetec::PopedomInfoList& list() const;
  inline ::isafetec::PopedomInfoList* mutable_list();
  inline ::isafetec::PopedomInfoList* release_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.PopedomInfoNode)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_maintype();
  inline void clear_has_maintype();
  inline void set_has_mainname();
  inline void clear_has_mainname();
  inline void set_has_mainiconpath();
  inline void clear_has_mainiconpath();
  inline void set_has_list();
  inline void clear_has_list();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 maintype_;
  ::std::string* mainname_;
  ::std::string* mainiconpath_;
  ::isafetec::PopedomInfoList* list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_popedom_2eproto();
  friend void protobuf_AssignDesc_popedom_2eproto();
  friend void protobuf_ShutdownFile_popedom_2eproto();
  
  void InitAsDefaultInstance();
  static PopedomInfoNode* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PopedomNodeList : public ::google::protobuf::Message {
 public:
  PopedomNodeList();
  virtual ~PopedomNodeList();
  
  PopedomNodeList(const PopedomNodeList& from);
  
  inline PopedomNodeList& operator=(const PopedomNodeList& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PopedomNodeList& default_instance();
  
  void Swap(PopedomNodeList* other);
  
  // implements Message ----------------------------------------------
  
  PopedomNodeList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PopedomNodeList& from);
  void MergeFrom(const PopedomNodeList& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .isafetec.PopedomInfoNode list = 1;
  inline int list_size() const;
  inline void clear_list();
  static const int kListFieldNumber = 1;
  inline const ::isafetec::PopedomInfoNode& list(int index) const;
  inline ::isafetec::PopedomInfoNode* mutable_list(int index);
  inline ::isafetec::PopedomInfoNode* PopedomNodeList::list_ReleaseAt(int index); 
  inline void PopedomNodeList::list_RemoveAt(int index); 
  inline ::isafetec::PopedomInfoNode* add_list();
  inline const ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfoNode >&
      list() const;
  inline ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfoNode >*
      mutable_list();
  
  // @@protoc_insertion_point(class_scope:isafetec.PopedomNodeList)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::isafetec::PopedomInfoNode > list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_popedom_2eproto();
  friend void protobuf_AssignDesc_popedom_2eproto();
  friend void protobuf_ShutdownFile_popedom_2eproto();
  
  void InitAsDefaultInstance();
  static PopedomNodeList* default_instance_;
};
// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace isafetec

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_popedom_2eproto__INCLUDED
