// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thirdpaymessage.proto

#ifndef PROTOBUF_thirdpaymessage_2eproto__INCLUDED
#define PROTOBUF_thirdpaymessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "mobile.pb.h"
#include "printermessage.pb.h"
// @@protoc_insertion_point(includes)

namespace isafetec {

// Internal implementation detail -- do not call these.
void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
void protobuf_AssignDesc_thirdpaymessage_2eproto();
void protobuf_ShutdownFile_thirdpaymessage_2eproto();

class LoginQrcodeRequest;
class LoginQrcodeResponse;
class EquipUserOnlineInfo;
class ThirdPartLoginEquip;
class CommonResult;
class PrtStationOrderInfo;
class PrtStationOrderHeader;

// ===================================================================

class LIBPROTOBUF_EXPORT LoginQrcodeRequest : public ::google::protobuf::Message {
 public:
  LoginQrcodeRequest();
  virtual ~LoginQrcodeRequest();
  
  LoginQrcodeRequest(const LoginQrcodeRequest& from);
  
  inline LoginQrcodeRequest& operator=(const LoginQrcodeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginQrcodeRequest& default_instance();
  
  void Swap(LoginQrcodeRequest* other);
  
  // implements Message ----------------------------------------------
  
  LoginQrcodeRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginQrcodeRequest& from);
  void MergeFrom(const LoginQrcodeRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 equipid = 1;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 1;
  inline ::google::protobuf::int32 equipid() const;
  inline void set_equipid(::google::protobuf::int32 value);
  
  // optional int32 qrtype = 2;
  inline bool has_qrtype() const;
  inline void clear_qrtype();
  static const int kQrtypeFieldNumber = 2;
  inline ::google::protobuf::int32 qrtype() const;
  inline void set_qrtype(::google::protobuf::int32 value);
  
  // optional uint32 time_stamp = 3;
  inline bool has_time_stamp() const;
  inline void clear_time_stamp();
  static const int kTimeStampFieldNumber = 3;
  inline ::google::protobuf::uint32 time_stamp() const;
  inline void set_time_stamp(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.LoginQrcodeRequest)
 private:
  inline void set_has_equipid();
  inline void clear_has_equipid();
  inline void set_has_qrtype();
  inline void clear_has_qrtype();
  inline void set_has_time_stamp();
  inline void clear_has_time_stamp();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 equipid_;
  ::google::protobuf::int32 qrtype_;
  ::google::protobuf::uint32 time_stamp_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static LoginQrcodeRequest* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT LoginQrcodeResponse : public ::google::protobuf::Message {
 public:
  LoginQrcodeResponse();
  virtual ~LoginQrcodeResponse();
  
  LoginQrcodeResponse(const LoginQrcodeResponse& from);
  
  inline LoginQrcodeResponse& operator=(const LoginQrcodeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginQrcodeResponse& default_instance();
  
  void Swap(LoginQrcodeResponse* other);
  
  // implements Message ----------------------------------------------
  
  LoginQrcodeResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginQrcodeResponse& from);
  void MergeFrom(const LoginQrcodeResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 equipid = 1;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 1;
  inline ::google::protobuf::int32 equipid() const;
  inline void set_equipid(::google::protobuf::int32 value);
  
  // optional int32 qrtype = 2;
  inline bool has_qrtype() const;
  inline void clear_qrtype();
  static const int kQrtypeFieldNumber = 2;
  inline ::google::protobuf::int32 qrtype() const;
  inline void set_qrtype(::google::protobuf::int32 value);
  
  // optional uint32 time_stamp = 3;
  inline bool has_time_stamp() const;
  inline void clear_time_stamp();
  static const int kTimeStampFieldNumber = 3;
  inline ::google::protobuf::uint32 time_stamp() const;
  inline void set_time_stamp(::google::protobuf::uint32 value);
  
  // optional int32 errcode = 4;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrcodeFieldNumber = 4;
  inline ::google::protobuf::int32 errcode() const;
  inline void set_errcode(::google::protobuf::int32 value);
  
  // optional string errmsg = 5;
  inline bool has_errmsg() const;
  inline void clear_errmsg();
  static const int kErrmsgFieldNumber = 5;
  inline const ::std::string& errmsg() const;
  inline void set_errmsg(const ::std::string& value);
  inline void set_errmsg(const char* value);
  inline void set_errmsg(const char* value, size_t size);
  inline ::std::string* mutable_errmsg();
  inline ::std::string* release_errmsg();
  
  // optional string qrstring = 6;
  inline bool has_qrstring() const;
  inline void clear_qrstring();
  static const int kQrstringFieldNumber = 6;
  inline const ::std::string& qrstring() const;
  inline void set_qrstring(const ::std::string& value);
  inline void set_qrstring(const char* value);
  inline void set_qrstring(const char* value, size_t size);
  inline ::std::string* mutable_qrstring();
  inline ::std::string* release_qrstring();
  
  // @@protoc_insertion_point(class_scope:isafetec.LoginQrcodeResponse)
 private:
  inline void set_has_equipid();
  inline void clear_has_equipid();
  inline void set_has_qrtype();
  inline void clear_has_qrtype();
  inline void set_has_time_stamp();
  inline void clear_has_time_stamp();
  inline void set_has_errcode();
  inline void clear_has_errcode();
  inline void set_has_errmsg();
  inline void clear_has_errmsg();
  inline void set_has_qrstring();
  inline void clear_has_qrstring();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 equipid_;
  ::google::protobuf::int32 qrtype_;
  ::google::protobuf::uint32 time_stamp_;
  ::google::protobuf::int32 errcode_;
  ::std::string* errmsg_;
  ::std::string* qrstring_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static LoginQrcodeResponse* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT EquipUserOnlineInfo : public ::google::protobuf::Message {
 public:
  EquipUserOnlineInfo();
  virtual ~EquipUserOnlineInfo();
  
  EquipUserOnlineInfo(const EquipUserOnlineInfo& from);
  
  inline EquipUserOnlineInfo& operator=(const EquipUserOnlineInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const EquipUserOnlineInfo& default_instance();
  
  void Swap(EquipUserOnlineInfo* other);
  
  // implements Message ----------------------------------------------
  
  EquipUserOnlineInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EquipUserOnlineInfo& from);
  void MergeFrom(const EquipUserOnlineInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 equipid = 1;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 1;
  inline ::google::protobuf::int32 equipid() const;
  inline void set_equipid(::google::protobuf::int32 value);
  
  // required int32 userid = 2;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUseridFieldNumber = 2;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);
  
  // optional int32 login_type = 3;
  inline bool has_login_type() const;
  inline void clear_login_type();
  static const int kLoginTypeFieldNumber = 3;
  inline ::google::protobuf::int32 login_type() const;
  inline void set_login_type(::google::protobuf::int32 value);
  
  // optional string update_time = 4;
  inline bool has_update_time() const;
  inline void clear_update_time();
  static const int kUpdateTimeFieldNumber = 4;
  inline const ::std::string& update_time() const;
  inline void set_update_time(const ::std::string& value);
  inline void set_update_time(const char* value);
  inline void set_update_time(const char* value, size_t size);
  inline ::std::string* mutable_update_time();
  inline ::std::string* release_update_time();
  
  // @@protoc_insertion_point(class_scope:isafetec.EquipUserOnlineInfo)
 private:
  inline void set_has_equipid();
  inline void clear_has_equipid();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_login_type();
  inline void clear_has_login_type();
  inline void set_has_update_time();
  inline void clear_has_update_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 equipid_;
  ::google::protobuf::int32 userid_;
  ::std::string* update_time_;
  ::google::protobuf::int32 login_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static EquipUserOnlineInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT ThirdPartLoginEquip : public ::google::protobuf::Message {
 public:
  ThirdPartLoginEquip();
  virtual ~ThirdPartLoginEquip();
  
  ThirdPartLoginEquip(const ThirdPartLoginEquip& from);
  
  inline ThirdPartLoginEquip& operator=(const ThirdPartLoginEquip& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ThirdPartLoginEquip& default_instance();
  
  void Swap(ThirdPartLoginEquip* other);
  
  // implements Message ----------------------------------------------
  
  ThirdPartLoginEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ThirdPartLoginEquip& from);
  void MergeFrom(const ThirdPartLoginEquip& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 equipid = 1;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 1;
  inline ::google::protobuf::int32 equipid() const;
  inline void set_equipid(::google::protobuf::int32 value);
  
  // required string accountno = 2;
  inline bool has_accountno() const;
  inline void clear_accountno();
  static const int kAccountnoFieldNumber = 2;
  inline const ::std::string& accountno() const;
  inline void set_accountno(const ::std::string& value);
  inline void set_accountno(const char* value);
  inline void set_accountno(const char* value, size_t size);
  inline ::std::string* mutable_accountno();
  inline ::std::string* release_accountno();
  
  // optional int32 userid = 3;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUseridFieldNumber = 3;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);
  
  // optional int32 login_type = 4;
  inline bool has_login_type() const;
  inline void clear_login_type();
  static const int kLoginTypeFieldNumber = 4;
  inline ::google::protobuf::int32 login_type() const;
  inline void set_login_type(::google::protobuf::int32 value);
  
  // optional string session_id = 5;
  inline bool has_session_id() const;
  inline void clear_session_id();
  static const int kSessionIdFieldNumber = 5;
  inline const ::std::string& session_id() const;
  inline void set_session_id(const ::std::string& value);
  inline void set_session_id(const char* value);
  inline void set_session_id(const char* value, size_t size);
  inline ::std::string* mutable_session_id();
  inline ::std::string* release_session_id();
  
  // optional .isafetec.CommonResult result = 6;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 6;
  inline const ::isafetec::CommonResult& result() const;
  inline ::isafetec::CommonResult* mutable_result();
  inline ::isafetec::CommonResult* release_result();
  
  // @@protoc_insertion_point(class_scope:isafetec.ThirdPartLoginEquip)
 private:
  inline void set_has_equipid();
  inline void clear_has_equipid();
  inline void set_has_accountno();
  inline void clear_has_accountno();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_login_type();
  inline void clear_has_login_type();
  inline void set_has_session_id();
  inline void clear_has_session_id();
  inline void set_has_result();
  inline void clear_has_result();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* accountno_;
  ::google::protobuf::int32 equipid_;
  ::google::protobuf::int32 userid_;
  ::std::string* session_id_;
  ::isafetec::CommonResult* result_;
  ::google::protobuf::int32 login_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static ThirdPartLoginEquip* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT CommonResult : public ::google::protobuf::Message {
 public:
  CommonResult();
  virtual ~CommonResult();
  
  CommonResult(const CommonResult& from);
  
  inline CommonResult& operator=(const CommonResult& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CommonResult& default_instance();
  
  void Swap(CommonResult* other);
  
  // implements Message ----------------------------------------------
  
  CommonResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommonResult& from);
  void MergeFrom(const CommonResult& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 errcode = 1;
  inline bool has_errcode() const;
  inline void clear_errcode();
  static const int kErrcodeFieldNumber = 1;
  inline ::google::protobuf::int32 errcode() const;
  inline void set_errcode(::google::protobuf::int32 value);
  
  // optional string errmsg = 2;
  inline bool has_errmsg() const;
  inline void clear_errmsg();
  static const int kErrmsgFieldNumber = 2;
  inline const ::std::string& errmsg() const;
  inline void set_errmsg(const ::std::string& value);
  inline void set_errmsg(const char* value);
  inline void set_errmsg(const char* value, size_t size);
  inline ::std::string* mutable_errmsg();
  inline ::std::string* release_errmsg();
  
  // @@protoc_insertion_point(class_scope:isafetec.CommonResult)
 private:
  inline void set_has_errcode();
  inline void clear_has_errcode();
  inline void set_has_errmsg();
  inline void clear_has_errmsg();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* errmsg_;
  ::google::protobuf::int32 errcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static CommonResult* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PrtStationOrderInfo : public ::google::protobuf::Message {
 public:
  PrtStationOrderInfo();
  virtual ~PrtStationOrderInfo();
  
  PrtStationOrderInfo(const PrtStationOrderInfo& from);
  
  inline PrtStationOrderInfo& operator=(const PrtStationOrderInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PrtStationOrderInfo& default_instance();
  
  void Swap(PrtStationOrderInfo* other);
  
  // implements Message ----------------------------------------------
  
  PrtStationOrderInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrtStationOrderInfo& from);
  void MergeFrom(const PrtStationOrderInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string OrderNo = 2;
  inline bool has_orderno() const;
  inline void clear_orderno();
  static const int kOrderNoFieldNumber = 2;
  inline const ::std::string& orderno() const;
  inline void set_orderno(const ::std::string& value);
  inline void set_orderno(const char* value);
  inline void set_orderno(const char* value, size_t size);
  inline ::std::string* mutable_orderno();
  inline ::std::string* release_orderno();
  
  // required int32 UserId = 3;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 3;
  inline ::google::protobuf::int32 userid() const;
  inline void set_userid(::google::protobuf::int32 value);
  
  // required int32 AccountId = 4;
  inline bool has_accountid() const;
  inline void clear_accountid();
  static const int kAccountIdFieldNumber = 4;
  inline ::google::protobuf::int32 accountid() const;
  inline void set_accountid(::google::protobuf::int32 value);
  
  // optional string AccountName = 5;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 5;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  
  // optional string RealName = 6;
  inline bool has_realname() const;
  inline void clear_realname();
  static const int kRealNameFieldNumber = 6;
  inline const ::std::string& realname() const;
  inline void set_realname(const ::std::string& value);
  inline void set_realname(const char* value);
  inline void set_realname(const char* value, size_t size);
  inline ::std::string* mutable_realname();
  inline ::std::string* release_realname();
  
  // required int32 PrtId = 7;
  inline bool has_prtid() const;
  inline void clear_prtid();
  static const int kPrtIdFieldNumber = 7;
  inline ::google::protobuf::int32 prtid() const;
  inline void set_prtid(::google::protobuf::int32 value);
  
  // required int32 SpendMoney = 8;
  inline bool has_spendmoney() const;
  inline void clear_spendmoney();
  static const int kSpendMoneyFieldNumber = 8;
  inline ::google::protobuf::int32 spendmoney() const;
  inline void set_spendmoney(::google::protobuf::int32 value);
  
  // optional .isafetec.Pay_Type PayType = 9;
  inline bool has_paytype() const;
  inline void clear_paytype();
  static const int kPayTypeFieldNumber = 9;
  inline isafetec::Pay_Type paytype() const;
  inline void set_paytype(isafetec::Pay_Type value);
  
  // optional string PayAccount = 10;
  inline bool has_payaccount() const;
  inline void clear_payaccount();
  static const int kPayAccountFieldNumber = 10;
  inline const ::std::string& payaccount() const;
  inline void set_payaccount(const ::std::string& value);
  inline void set_payaccount(const char* value);
  inline void set_payaccount(const char* value, size_t size);
  inline ::std::string* mutable_payaccount();
  inline ::std::string* release_payaccount();
  
  // optional string PayCompany = 11;
  inline bool has_paycompany() const;
  inline void clear_paycompany();
  static const int kPayCompanyFieldNumber = 11;
  inline const ::std::string& paycompany() const;
  inline void set_paycompany(const ::std::string& value);
  inline void set_paycompany(const char* value);
  inline void set_paycompany(const char* value, size_t size);
  inline ::std::string* mutable_paycompany();
  inline ::std::string* release_paycompany();
  
  // optional int32 PayMoney = 12;
  inline bool has_paymoney() const;
  inline void clear_paymoney();
  static const int kPayMoneyFieldNumber = 12;
  inline ::google::protobuf::int32 paymoney() const;
  inline void set_paymoney(::google::protobuf::int32 value);
  
  // optional int32 PayRedPacket = 13;
  inline bool has_payredpacket() const;
  inline void clear_payredpacket();
  static const int kPayRedPacketFieldNumber = 13;
  inline ::google::protobuf::int32 payredpacket() const;
  inline void set_payredpacket(::google::protobuf::int32 value);
  
  // optional int32 PayPreferential = 14;
  inline bool has_paypreferential() const;
  inline void clear_paypreferential();
  static const int kPayPreferentialFieldNumber = 14;
  inline ::google::protobuf::int32 paypreferential() const;
  inline void set_paypreferential(::google::protobuf::int32 value);
  
  // optional .isafetec.JOB_TYPE JobType = 15;
  inline bool has_jobtype() const;
  inline void clear_jobtype();
  static const int kJobTypeFieldNumber = 15;
  inline isafetec::JOB_TYPE jobtype() const;
  inline void set_jobtype(isafetec::JOB_TYPE value);
  
  // repeated int32 JobIdList = 16;
  inline int jobidlist_size() const;
  inline void clear_jobidlist();
  static const int kJobIdListFieldNumber = 16;
  inline ::google::protobuf::int32 jobidlist(int index) const;
  inline void set_jobidlist(int index, ::google::protobuf::int32 value);
  inline void add_jobidlist(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      jobidlist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_jobidlist();
  
  // optional int32 TotalPage = 17;
  inline bool has_totalpage() const;
  inline void clear_totalpage();
  static const int kTotalPageFieldNumber = 17;
  inline ::google::protobuf::int32 totalpage() const;
  inline void set_totalpage(::google::protobuf::int32 value);
  
  // optional int32 RealPage = 18;
  inline bool has_realpage() const;
  inline void clear_realpage();
  static const int kRealPageFieldNumber = 18;
  inline ::google::protobuf::int32 realpage() const;
  inline void set_realpage(::google::protobuf::int32 value);
  
  // optional int32 Color = 19;
  inline bool has_color() const;
  inline void clear_color();
  static const int kColorFieldNumber = 19;
  inline ::google::protobuf::int32 color() const;
  inline void set_color(::google::protobuf::int32 value);
  
  // optional int32 Copies = 20;
  inline bool has_copies() const;
  inline void clear_copies();
  static const int kCopiesFieldNumber = 20;
  inline ::google::protobuf::int32 copies() const;
  inline void set_copies(::google::protobuf::int32 value);
  
  // optional double CreateOn = 21;
  inline bool has_createon() const;
  inline void clear_createon();
  static const int kCreateOnFieldNumber = 21;
  inline double createon() const;
  inline void set_createon(double value);
  
  // optional double PayTime = 22;
  inline bool has_paytime() const;
  inline void clear_paytime();
  static const int kPayTimeFieldNumber = 22;
  inline double paytime() const;
  inline void set_paytime(double value);
  
  // optional .isafetec.Pay_State PayState = 23;
  inline bool has_paystate() const;
  inline void clear_paystate();
  static const int kPayStateFieldNumber = 23;
  inline isafetec::Pay_State paystate() const;
  inline void set_paystate(isafetec::Pay_State value);
  
  // optional .isafetec.Job_Op_State JobOpState = 24;
  inline bool has_jobopstate() const;
  inline void clear_jobopstate();
  static const int kJobOpStateFieldNumber = 24;
  inline isafetec::Job_Op_State jobopstate() const;
  inline void set_jobopstate(isafetec::Job_Op_State value);
  
  // optional double JobCompleteTime = 25;
  inline bool has_jobcompletetime() const;
  inline void clear_jobcompletetime();
  static const int kJobCompleteTimeFieldNumber = 25;
  inline double jobcompletetime() const;
  inline void set_jobcompletetime(double value);
  
  // optional double JobCompleteNotifyTime = 26;
  inline bool has_jobcompletenotifytime() const;
  inline void clear_jobcompletenotifytime();
  static const int kJobCompleteNotifyTimeFieldNumber = 26;
  inline double jobcompletenotifytime() const;
  inline void set_jobcompletenotifytime(double value);
  
  // optional string PaymentUrl = 27;
  inline bool has_paymenturl() const;
  inline void clear_paymenturl();
  static const int kPaymentUrlFieldNumber = 27;
  inline const ::std::string& paymenturl() const;
  inline void set_paymenturl(const ::std::string& value);
  inline void set_paymenturl(const char* value);
  inline void set_paymenturl(const char* value, size_t size);
  inline ::std::string* mutable_paymenturl();
  inline ::std::string* release_paymenturl();
  
  // optional string comment = 28;
  inline bool has_comment() const;
  inline void clear_comment();
  static const int kCommentFieldNumber = 28;
  inline const ::std::string& comment() const;
  inline void set_comment(const ::std::string& value);
  inline void set_comment(const char* value);
  inline void set_comment(const char* value, size_t size);
  inline ::std::string* mutable_comment();
  inline ::std::string* release_comment();
  
  // optional int32 OrgID = 29;
  inline bool has_orgid() const;
  inline void clear_orgid();
  static const int kOrgIDFieldNumber = 29;
  inline ::google::protobuf::int32 orgid() const;
  inline void set_orgid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.PrtStationOrderInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_orderno();
  inline void clear_has_orderno();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_accountid();
  inline void clear_has_accountid();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_realname();
  inline void clear_has_realname();
  inline void set_has_prtid();
  inline void clear_has_prtid();
  inline void set_has_spendmoney();
  inline void clear_has_spendmoney();
  inline void set_has_paytype();
  inline void clear_has_paytype();
  inline void set_has_payaccount();
  inline void clear_has_payaccount();
  inline void set_has_paycompany();
  inline void clear_has_paycompany();
  inline void set_has_paymoney();
  inline void clear_has_paymoney();
  inline void set_has_payredpacket();
  inline void clear_has_payredpacket();
  inline void set_has_paypreferential();
  inline void clear_has_paypreferential();
  inline void set_has_jobtype();
  inline void clear_has_jobtype();
  inline void set_has_totalpage();
  inline void clear_has_totalpage();
  inline void set_has_realpage();
  inline void clear_has_realpage();
  inline void set_has_color();
  inline void clear_has_color();
  inline void set_has_copies();
  inline void clear_has_copies();
  inline void set_has_createon();
  inline void clear_has_createon();
  inline void set_has_paytime();
  inline void clear_has_paytime();
  inline void set_has_paystate();
  inline void clear_has_paystate();
  inline void set_has_jobopstate();
  inline void clear_has_jobopstate();
  inline void set_has_jobcompletetime();
  inline void clear_has_jobcompletetime();
  inline void set_has_jobcompletenotifytime();
  inline void clear_has_jobcompletenotifytime();
  inline void set_has_paymenturl();
  inline void clear_has_paymenturl();
  inline void set_has_comment();
  inline void clear_has_comment();
  inline void set_has_orgid();
  inline void clear_has_orgid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* orderno_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 userid_;
  ::std::string* accountname_;
  ::google::protobuf::int32 accountid_;
  ::google::protobuf::int32 prtid_;
  ::std::string* realname_;
  ::google::protobuf::int32 spendmoney_;
  int paytype_;
  ::std::string* payaccount_;
  ::std::string* paycompany_;
  ::google::protobuf::int32 paymoney_;
  ::google::protobuf::int32 payredpacket_;
  ::google::protobuf::int32 paypreferential_;
  int jobtype_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > jobidlist_;
  ::google::protobuf::int32 totalpage_;
  ::google::protobuf::int32 realpage_;
  ::google::protobuf::int32 color_;
  ::google::protobuf::int32 copies_;
  double createon_;
  double paytime_;
  int paystate_;
  int jobopstate_;
  double jobcompletetime_;
  double jobcompletenotifytime_;
  ::std::string* paymenturl_;
  ::std::string* comment_;
  ::google::protobuf::int32 orgid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(29 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static PrtStationOrderInfo* default_instance_;
};
// -------------------------------------------------------------------

class LIBPROTOBUF_EXPORT PrtStationOrderHeader : public ::google::protobuf::Message {
 public:
  PrtStationOrderHeader();
  virtual ~PrtStationOrderHeader();
  
  PrtStationOrderHeader(const PrtStationOrderHeader& from);
  
  inline PrtStationOrderHeader& operator=(const PrtStationOrderHeader& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PrtStationOrderHeader& default_instance();
  
  void Swap(PrtStationOrderHeader* other);
  
  // implements Message ----------------------------------------------
  
  PrtStationOrderHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrtStationOrderHeader& from);
  void MergeFrom(const PrtStationOrderHeader& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 SerFlag = 1;
  inline bool has_serflag() const;
  inline void clear_serflag();
  static const int kSerFlagFieldNumber = 1;
  inline ::google::protobuf::int32 serflag() const;
  inline void set_serflag(::google::protobuf::int32 value);
  
  // optional int32 Equipid = 2;
  inline bool has_equipid() const;
  inline void clear_equipid();
  static const int kEquipidFieldNumber = 2;
  inline ::google::protobuf::int32 equipid() const;
  inline void set_equipid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:isafetec.PrtStationOrderHeader)
 private:
  inline void set_has_serflag();
  inline void clear_has_serflag();
  inline void set_has_equipid();
  inline void clear_has_equipid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 serflag_;
  ::google::protobuf::int32 equipid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_thirdpaymessage_2eproto();
  friend void protobuf_AssignDesc_thirdpaymessage_2eproto();
  friend void protobuf_ShutdownFile_thirdpaymessage_2eproto();
  
  void InitAsDefaultInstance();
  static PrtStationOrderHeader* default_instance_;
};
// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace isafetec

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_thirdpaymessage_2eproto__INCLUDED
